web:
  extends:
    file: docker-compose.base.yml
    service: web
  ports:
    - "80:5000"
  environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud_credentials/aipcloud-407c70054e81.json
  command: python app.py
