server:
  restart: always
  image: nginx
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
    - /etc/letsencrypt/:/etc/letsencrypt/
      #- ./app/static:/app/static
  links:
    - web:web
  ports:
    - "80:80"
    - "443:443"

web:
  extends:
    file: docker-compose.base.yml
    service: web
  expose:
    - "8000"
  command: gunicorn wsgi:app -b :8000 --name app --log-level=debug --log-file=- --config gunicorn.conf.py --timeout 500 -w 4
